services:
- docker
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- eval $(aws ecr get-login --no-include-email --region us-east-1)
- docker build -t my-api .
- docker tag my-api:latest 989002346127.dkr.ecr.us-east-1.amazonaws.com/my-api:latest
- docker push 989002346127.dkr.ecr.us-east-1.amazonaws.com/my-api:latest
env:
  global:
  - secure: QHxXmEpFNANSMhL3J64clemeUmNycTKfYhWrdKdMUrrolNktAx+Uv1PdT28K1OFe19q4OLHWy7nmphEE0WbVhYXE+KOEXNhPhldSE6+evnR+IqKW3OTBgcoJa9fqYeq2dRWeSEvMNQ1m2RajAxrtnYS6P7D2DxdV+OQCWNebdVvgeKZxS1+Jh3xWrQJQZX6hbR9zc0HP3uCR0wWr0pMJItpa6tWR/t3bq3EybpMD4CqjhNbGv0rp1m6C7VifkcoqFFhVobSmut3ADZWUoJU526FJZDx0WuiASssDBhNfsB1R3Npoj2R3Y2NBqauzsOG+6D0UZ/1QJ6WBxYaYkg+P0xQRz2wtiGNlgZJd7u/BQo7NaHcU1CznrY7QaxkULBbGJNgqrglPFnEUtvSYsVVrsZdeDsyDwujgb1j/5U34jhcb03hXXIu7GOA/Otb6Is1Q8zzBmxPyxtzZv4x42OmYrDS0C4yhHDmK/6bzMFU5jNxnlyDAhttEtQSHskTKe1jQVdBkiAJ1ih+UDT4ouTkIx69juETk3uWZ7eaRBp3OYF1c6kitAue7PKX1AV3vd9NtEJy3rAjO3PMAAtcqqWu3nuMRlX60b6znZXK7aQ8rbpw25qRdzFB9eIv9LA014q1PATMf34eOgmGF9+hi1kjLliD5K+F5ksEckrbFfxUYLTY=
  - secure: R/38OlYiuG/Fq81zZ5eetdxtu8ud41esL74AMg968zmLv8gZWNyFgNHpNbdI/rMU3LVE6dcQL6y4KyZmH3b+xqszl7Yvp04CxFtHx899VyuJl2gJpIW0JUkehm3LrQonvD8XhfNc/U96/f1EZif8wxSOeqmrM7X0QTwpTEEfEsbMNPYmm2KBpyip1xQ7tx9SAUOtEgQw9MZQQ3QCD5SwbTNrLVxP8fVeCWzXXNEy94t34RbrWd+dWrljncuYB3wOovCR/QQOYyAQ326R4URHkJnzQKcx41kOqKNGwguGcWvJhdDUI/6QV0igVmESh7iOIiCg1Vd4ehrsPydiMvq0vP/bHMBOzVyok6UgFawY6+hYw6w180Q0lvrpu2gJwYhm134IpwO4SJbrU53V/Fs4Le2BUt6KzKOeEdvKeQ25gefvGeJfA3LB7pfJFovR3Y16o12Lz3BfE51An03lpjdCwMIpiQyUZCKihp7DcEyXJOGH7uyURfOq2pPHVxcD7CQnchCu1MYQFGPplvgAO3HMWnruEfWMx7KPb2LmRvSjKdiTDJI3hiPAc4wJBQLZPZ/W0vPnEn8JSw3zTj+Dnsqm5WEBCbgsh4UzWWIP37+U9NeQft5QPcDQmUMvxkq1R0DS+S9OEXOPWZejJNoyXcXKTi/4WKHmqZ/3RL5z5st4F28=
